export const state = {
  title: '@magic-modules',
  description: '@magic-modules. building blocks for your @magic app.',
  logotext: '@magic-modules',
  logo: '/logo.png',
  menu: [
    {
      to: '/#gl-magic-modules',
      text: 'magic-modules',
      items: [
        { to: '-li-accordion', text: 'accordion' },
        { to: '-li-gdpr', text: 'gdpr' },
        { to: '-li-git-badges', text: 'git-badges' },
        { to: '-li-git-list', text: 'git-list' },
        { to: '-li-hero', text: 'hero' },
        { to: '-li-language-switch', text: 'language-switch' },
        { to: '-li-library-list', text: 'library-list' },
        { to: '-li-light-switch', text: 'light-switch' },
        { to: '-li-messages', text: 'messages' },
        { to: '-li-module-list', text: 'module-list' },
        { to: '-li-pre', text: 'pre' },
        { to: '-li-sound-cloud', text: 'sound-cloud' },
        { to: '-li-theme-list', text: 'theme-list' },
        { to: '-li-theme-vars', text: 'theme-vars' },
        { to: '-li-video-embed', text: 'video-embed' },
        { to: '-li-xkcd', text: 'xkcd embed' },
      ],
    },
  ],
}
